// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package quasizero

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	// Request/command code.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Custom metadata.
	Metadata map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Raw payload.
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Request) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Request) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Response struct {
	// Optional client error.
	ClientError string `protobuf:"bytes,1,opt,name=client_error,json=clientError,proto3" json:"client_error,omitempty"`
	// Custom metadata.
	Metadata map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Raw payload.
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetClientError() string {
	if m != nil {
		return m.ClientError
	}
	return ""
}

func (m *Response) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Response) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "blacksquaremedia.quasizero.Request")
	proto.RegisterMapType((map[string]string)(nil), "blacksquaremedia.quasizero.Request.MetadataEntry")
	proto.RegisterType((*Response)(nil), "blacksquaremedia.quasizero.Response")
	proto.RegisterMapType((map[string]string)(nil), "blacksquaremedia.quasizero.Response.MetadataEntry")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xd9, 0xc4, 0xda, 0x76, 0x52, 0x45, 0x06, 0x0f, 0x4b, 0x4f, 0xb1, 0xa7, 0x9c, 0x16,
	0xac, 0x17, 0xd1, 0x9b, 0xd0, 0x63, 0x3d, 0xec, 0xd1, 0x8b, 0x4c, 0x93, 0x41, 0x42, 0x93, 0x6c,
	0xb2, 0xbb, 0x11, 0xe2, 0xdf, 0xf3, 0x2f, 0xf8, 0x83, 0xa4, 0x49, 0x2c, 0x88, 0xe8, 0xd1, 0xdb,
	0xbc, 0x07, 0xef, 0xe3, 0x3d, 0x06, 0xce, 0x4b, 0x76, 0x8e, 0x5e, 0xd8, 0xa9, 0xda, 0x1a, 0x6f,
	0x70, 0xb9, 0x2b, 0x28, 0xdd, 0xbb, 0xa6, 0x25, 0xcb, 0x25, 0x67, 0x39, 0xa9, 0xa6, 0x25, 0x97,
	0xbf, 0xb1, 0x35, 0xab, 0x77, 0x01, 0x53, 0xcd, 0x4d, 0xcb, 0xce, 0x23, 0xc2, 0x49, 0x6a, 0x32,
	0x96, 0x22, 0x16, 0xc9, 0x44, 0xf7, 0x37, 0x6e, 0x61, 0x56, 0xb2, 0xa7, 0x8c, 0x3c, 0xc9, 0x20,
	0x0e, 0x93, 0x68, 0x7d, 0xad, 0x7e, 0xc7, 0xa9, 0x11, 0xa5, 0xb6, 0x63, 0x66, 0x53, 0x79, 0xdb,
	0xe9, 0x23, 0x02, 0x25, 0x4c, 0x6b, 0xea, 0x0a, 0x43, 0x99, 0x0c, 0x63, 0x91, 0x2c, 0xf4, 0x97,
	0x5c, 0xde, 0xc3, 0xd9, 0xb7, 0x10, 0x5e, 0x40, 0xb8, 0xe7, 0xae, 0x2f, 0x33, 0xd7, 0x87, 0x13,
	0x2f, 0x61, 0xf2, 0x4a, 0x45, 0xcb, 0x32, 0xe8, 0xbd, 0x41, 0xdc, 0x05, 0xb7, 0x62, 0xf5, 0x21,
	0x60, 0xa6, 0xd9, 0xd5, 0xa6, 0x72, 0x8c, 0x57, 0xb0, 0x48, 0x8b, 0x9c, 0x2b, 0xff, 0xcc, 0xd6,
	0x1a, 0x3b, 0x12, 0xa2, 0xc1, 0xdb, 0x1c, 0x2c, 0x7c, 0xfc, 0xb1, 0x6a, 0xfd, 0xf7, 0xaa, 0x01,
	0xfd, 0xcf, 0xb3, 0x1e, 0xa2, 0xa7, 0xf9, 0xb1, 0xc4, 0xee, 0xb4, 0x7f, 0xe6, 0xcd, 0x67, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xda, 0x16, 0x8a, 0x0b, 0xde, 0x01, 0x00, 0x00,
}
